In [1]:
import numpy as np

El método `np.random.random(size)` retorna una matriz del tamaño indicado de números aleatorios extraidos de una distribución uniforme 

In [2]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    A = np.random.random([n,1])
    return A

In [3]:
randomization(4)

array([[0.03409096],
       [0.73920379],
       [0.25663426],
       [0.91671219]])

In [4]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.random([h, w])
    B = np.random.random([h, w])
    s = A + B
    return A, B, s

In [5]:
operations(3,5)

(array([[0.69184193, 0.23577983, 0.92011615, 0.43133919, 0.84117271],
        [0.71699336, 0.0429374 , 0.67555948, 0.51812721, 0.24639448],
        [0.22870474, 0.76900179, 0.02630764, 0.52480811, 0.96645364]]),
 array([[0.68671255, 0.71815845, 0.18126212, 0.30404507, 0.02267266],
        [0.89726803, 0.97432603, 0.75881472, 0.37693716, 0.6666177 ],
        [0.99179351, 0.13537544, 0.15657993, 0.45155248, 0.6621573 ]]),
 array([[1.37855448, 0.95393828, 1.10137827, 0.73538426, 0.86384537],
        [1.61426139, 1.01726343, 1.4343742 , 0.89506437, 0.91301217],
        [1.22049825, 0.90437723, 0.18288758, 0.97636059, 1.62861094]]))

El método `norm` del módulo de algebra lineal `linalg` de NumPy retorna la norma de un vector.

In [9]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    s = np.linalg.norm(A + B)
    return s

In [11]:
norm(np.array([2,3]), np.array([4,7]))

11.661903789690601

In [14]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    out = np.tanh(np.matmul(weights.transpose(), inputs))
    return out

In [15]:
inputs = np.array([[3],[4]])
weights = np.random.random([2,1])
neural_network(inputs, weights)

array([[0.99748912]])