In [1]:
import numpy as np

El método `np.random.random(size)` retorna una matriz del tamaño indicado de números aleatorios extraidos de una distribución uniforme 

In [2]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    A = np.random.random([n,1])
    return A

In [3]:
randomization(4)

array([[0.56619292],
       [0.45956873],
       [0.86534224],
       [0.76569553]])

In [4]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.random([h, w])
    B = np.random.random([h, w])
    s = A + B
    return A, B, s

In [5]:
operations(3,5)

(array([[0.68391116, 0.54906779, 0.44415005, 0.70451213, 0.34225747],
        [0.61141321, 0.02230252, 0.00750928, 0.28934292, 0.81193967],
        [0.15456772, 0.02964087, 0.72008289, 0.22132084, 0.82533653]]),
 array([[0.58567456, 0.73661706, 0.17625919, 0.5204812 , 0.02628717],
        [0.14563939, 0.23930779, 0.59815774, 0.94179445, 0.42916964],
        [0.83818177, 0.41259292, 0.723084  , 0.87077351, 0.56781571]]),
 array([[1.26958572, 1.28568485, 0.62040924, 1.22499333, 0.36854465],
        [0.7570526 , 0.2616103 , 0.60566702, 1.23113737, 1.24110931],
        [0.99274949, 0.44223379, 1.44316689, 1.09209435, 1.39315224]]))

El método `norm` del módulo de algebra lineal `linalg` de NumPy retorna la norma de un vector.

In [6]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    s = np.linalg.norm(A + B)
    return s

In [7]:
norm(np.array([2,3]), np.array([4,7]))

11.661903789690601

In [8]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    out = np.tanh(np.matmul(weights.transpose(), inputs))
    return out

In [9]:
inputs = np.array([[3],[4]])
weights = np.random.random([2,1])
neural_network(inputs, weights)

array([[0.9997164]])

In [18]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here
    result = 0.0
    if x <= y:
        result = x*y
    else:
        if y == 0.0:
            return "division by zero"
        result = x/y
    return result

In [19]:
scalar_function(5, 0)

'division by zero'

`scalar_function` solo puede manejar la entrada escalar, se puede utilizar la función `np.vectorize()` para convertirla en una función vectorizada. Hay que tener en cuenta que el argumento de entrada de `np.vectorize()` debe ser una función escalar, y la salida de `np.vectorize()` es una nueva función que puede manejar la entrada de vectores.

Se escribe una función vectorial `vector_function`, que aplicará la operación $f(x, y)$ definida ateriormente de forma inteligente con los vectores de entrada con la **misma dimensión** `x` e `y`.

In [45]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    if isinstance(x, int) and isinstance(y, int):
        return scalar_function(x, y)
    X = x
    Y = y
    if isinstance(x, list) and isinstance(y, list):
        X = np.array(x)
        Y = np.array(y)
    if isinstance(X, np.ndarray) and isinstance(Y, np.ndarray):
        if X.shape == Y.shape:
            func_vectorized = np.vectorize(scalar_function)
            return func_vectorized(X,Y)
    return 'Illegal parameters'
    

In [51]:
X = np.array([[3], [4], [5]])
Y = np.array([[6], [8], [7]])
AX = [[3], [4], [5]]
AY = [[6], [8], [7]]
x = 5
y = 7

In [54]:
def get_sum_metrics(predictions, metrics=[]):
    for i in range(3):
        metrics.append(lambda x: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics

In [60]:
def saludo(nombre, apellidos=[]):
    if len(apellidos)==0:
        apellidos.append('Moros')
        apellidos.append('Sales')
    print("Hola ", nombre, apellidos)

In [63]:
def main():
    saludo('gonzalo')
    saludo('gonzalo', ['fernandez'])

In [64]:
main()

Hola  gonzalo ['Moros', 'Sales']
Hola  gonzalo ['fernandez']
